# Nutanix Documentation Style Guide
# Grammar, Mechanics, and Style Conventions

style_guide:
  version: "1.0"
  title: "Nutanix Documentation Style Guide"
  description: "Essential rules for grammar, punctuation, and style to ensure consistency and readability"

  grammar_and_mechanics:
    capitalization:
      rule: "sentence_case"
      description: "Use sentence case for all titles, headings, and subheadings"
      guidelines:
        - "Capitalize only the first word and any proper nouns or acronyms"
      examples:
        correct:
          - "Resolve an alert for a CVM that is low on memory"
          - "Verifying the status of the Nutanix Cluster Check"
          - "How to upgrade AOS on a single-node cluster"
        incorrect:
          - "Resolve an Alert for a CVM That is Low on Memory"
          - "Verifying The Status Of The Nutanix Cluster Check"

    voice_and_mood:
      preferred: "active_voice_imperative"
      description: "Use active voice and imperative mood for clarity and directness"
      examples:
        do:
          - "Run the NCC health check."
          - "The CVM writes logs to this directory."
          - "Verify that the service is running."
        dont:
          - "The NCC health check should be run."
          - "Logs are written to this directory by the CVM."
          - "It should be verified that the service is running."

    contractions:
      policy: "use_sparingly"
      guidelines:
        - "Allowed when they improve tone and readability"
        - "Avoid in formal warnings or when clarity is at risk"
      examples:
        acceptable:
          - "Log in to Prism Element. From there, you'll be able to see the alert."
          - "It's important to verify the cluster status before proceeding."
        avoid:
          - "In critical warnings: 'Do not power off the node.' (Instead of 'Don't power off...')"
          - "Ambiguous contractions: should've, could've, etc."

    punctuation:
      oxford_comma:
        rule: "always_use"
        description: "Always use Oxford comma in lists of three or more items"
        examples:
          correct: "This issue affects AHV, ESXi, and Hyper-V."
          incorrect: "This issue affects AHV, ESXi and Hyper-V."
      
      hyphens:
        rule: "compound_adjectives"
        description: "Use in compound adjectives before nouns"
        examples:
          - "single-node cluster"
          - "command-line interface"
          - "health-check command"
      
      quotes:
        rule: "double_quotes"
        description: "Use double quotes for UI text, alerts, file names, or input strings"
        examples:
          - "Navigate to the Health dashboard and look for the alert \"Node Unreachable.\""
          - "Enter \"<CVM_IP_Address>\" when prompted."

    lists:
      numbered_lists:
        use_for: "sequential steps"
      bullet_lists:
        use_for: "non-sequential items"
      parallel_structure:
        required: true
        examples:
          correct:
            - "Checking the network configuration"
            - "Verifying the CVM status" 
            - "Running the NCC health check"
          incorrect:
            - "Check the network configuration"
            - "The CVM status should be verified"
            - "To run the NCC health check"

    length_guidelines:
      sentences:
        target_words: "15-20"
      paragraphs:
        target_sentences: "3-4"
        single_sentence_use: "for emphasis"

    code_commenting:
      purpose: "explain why a command is run"
      example: |
        # Check the status of the Stargate service on the local CVM
        # This service is critical for I/O operations
        CVM$ allssh "genesis status | grep -w stargate"

    callouts:
      placement: "before the relevant step"
      tone: "direct and neutral"
      types:
        note:
          description: "Helpful but not critical"
          example: "This process may take several minutes to complete."
        caution:
          description: "Risk of disruption or data loss"
          example: "Do not proceed unless you have a confirmed maintenance window."
        warning:
          description: "High risk of severe failure"
          example: "Running this command will irretrievably delete the storage container and all VMs within it."

  terminology:
    product_names:
      nutanix_cloud_platform:
        full_name: "Nutanix Cloud Platform"
        acronym: null
        notes: "Use full name"
      
      nutanix_aos:
        full_name: "Nutanix AOS"
        acronym: "AOS"
        notes: "Formerly Acropolis"
      
      nutanix_ahv:
        full_name: "Nutanix AHV"
        acronym: "AHV"
        notes: null
      
      nutanix_prism_central:
        full_name: "Nutanix Prism Central"
        acronym: "PC"
        notes: null
      
      nutanix_prism_element:
        full_name: "Nutanix Prism Element"
        acronym: "PE"
        notes: "Cluster-level UI"
      
      nutanix_cluster_check:
        full_name: "Nutanix Cluster Check"
        acronym: "NCC"
        notes: null
      
      distributed_storage_fabric:
        full_name: "Distributed Storage Fabric"
        acronym: "DSF"
        notes: null
      
      nutanix_flow:
        full_name: "Nutanix Flow Virtual Networking"
        acronym: "Flow"
        notes: null
      
      nutanix_cloud_clusters:
        full_name: "Nutanix Cloud Clusters"
        acronym: "NC2"
        notes: null

    abbreviation_rules:
      first_use: "Define acronyms on first use, then use consistently"
      examples:
        first_use: "Log in to the Controller VM (CVM) using SSH."
        subsequent_use: "Check the memory usage on the CVM."
      common_terms_exception: "For common terms (CVM, AHV, NCC), defining is best practice but may be skipped in short KBs"

    formatting:
      commands:
        format: "monospace"
        examples:
          - "ncli"
          - "acli" 
          - "ncc"
          - "allssh"
      
      processes:
        format: "monospace"
        examples:
          - "genesis"
          - "stargate"
          - "cassandra"
      
      paths:
        format: "monospace"
        examples:
          - "/home/nutanix/data/logs/"

    approved_phrasing:
      sensitive_actions:
        description: "Use calm, precise language"
        preferred_terms:
          unresponsive_node: "The node is unresponsive or unavailable."
          data_integrity: "There is a potential data integrity issue."
          manual_failover: "Perform a manual failover."
          service_stopped: "The service has stopped unexpectedly."
          drive_fault: "The drive has a fault."
        avoid_terms:
          - "The node is down/dead"
          - "The data is corrupted"
          - "Kill the service/process"
          - "The service crashed"
          - "The drive is bad/broken"

    definitions:
      inline_definitions:
        use_for: "simple terms"
        example: "You can connect using a terminal emulator that supports Secure Shell (SSH)."
      
      hyperlink_to_glossary:
        use_for: "complex or proprietary terms"
        example: "This check verifies the health of the Distributed Storage Fabric. For more details on DSF, see KB-XXXX."

    deprecated_terms:
      web_console:
        current_term: "Prism Element"
      prism:
        current_term: "Prism Element or Prism Central"
      container:
        current_term: "Storage Container"
      acropolis:
        current_term: "AOS"
      acropolis_hypervisor:
        current_term: "AHV"
      next_gen:
        current_term: "Remove; no longer useful"
      ng:
        current_term: "Remove; no longer useful"